name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container: ros:foxy

    steps:
    - name: Check out repo
      uses: actions/checkout@v2

    - name: Install missing dependencies
      run: |
        sudo apt-get update
        apt-get install -y curl
        rosdep update
        DEBIAN_FRONTEND=noninteractive rosdep install --from-paths . --ignore-src --rosdistro foxy -y

    - name: Setup Rust nightly
      run: |
        curl https://sh.rustup.rs -sSf > rustup.sh
        chmod +x rustup.sh
        ./rustup.sh --default-toolchain nightly --profile minimal -y

    - name: Build
      run: |
        . /opt/ros/foxy/setup.sh
        . ${HOME}/.cargo/env
        colcon build --event-handlers console_cohesion+

    - name: Run tests
      run: |
        . /opt/ros/foxy/setup.sh
        colcon test \
          --event-handlers console_cohesion+ \
          --return-code-on-test-failure